# Generated by Django 3.2.12 on 2023-11-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pay_increase', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('years_employed', models.IntegerField()),
                ('monday_start', models.TimeField(blank=True, default='00:00', null=True)),
                ('monday_end', models.TimeField(blank=True, default='00:00', null=True)),
                ('tuesday_start', models.TimeField(blank=True, default='00:00', null=True)),
                ('tuesday_end', models.TimeField(blank=True, default='00:00', null=True)),
                ('wednesday_start', models.TimeField(blank=True, default='00:00', null=True)),
                ('wednesday_end', models.TimeField(blank=True, default='00:00', null=True)),
                ('thursday_start', models.TimeField(blank=True, default='00:00', null=True)),
                ('thursday_end', models.TimeField(blank=True, default='00:00', null=True)),
                ('friday_start', models.TimeField(blank=True, default='00:00', null=True)),
                ('friday_end', models.TimeField(blank=True, default='00:00', null=True)),
                ('skills', models.ManyToManyField(to='main_app.Skill')),
            ],
        ),
    ]
