# Generated by Django 3.2.12 on 2023-11-29 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('level', models.CharField(choices=[('L1', 'LEVEL 1'), ('L2', 'LEVEL 2'), ('L3', 'LEVEL 3'), ('L4', 'LEVEL 4'), ('L5', 'LEVEL 5')], default='L1', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='friday_end',
            field=models.TimeField(blank=True, default='17:00', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='friday_start',
            field=models.TimeField(blank=True, default='08:00', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='monday_end',
            field=models.TimeField(blank=True, default='17:00', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='monday_start',
            field=models.TimeField(blank=True, default='08:00', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='thursday_end',
            field=models.TimeField(blank=True, default='17:00', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='thursday_start',
            field=models.TimeField(blank=True, default='08:00', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tuesday_end',
            field=models.TimeField(blank=True, default='17:00', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tuesday_start',
            field=models.TimeField(blank=True, default='08:00', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wednesday_end',
            field=models.TimeField(blank=True, default='17:00', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wednesday_start',
            field=models.TimeField(blank=True, default='8:00', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.position'),
        ),
    ]
