# Generated by Django 3.2.12 on 2023-11-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('L1', 'LEVEL 1'), ('L2', 'LEVEL 2'), ('L3', 'LEVEL 3'), ('L4', 'LEVEL 4'), ('L5', 'LEVEL 5')], default='L1', max_length=2),
        ),
    ]
