# Generated by Django 4.2.7 on 2023-11-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='date',
        ),
        migrations.AddField(
            model_name='skill',
            name='pay_increase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
