# Generated by Django 4.2.7 on 2023-11-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile_delete_user'),
        ('main_app', '0002_remove_skill_date_skill_pay_increase'),
    ]

    operations = [
    ]
