# Generated by Django 3.2.12 on 2023-11-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_merge_20231128_1455'),
        ('main_app', '0004_employee_skills'),
    ]

    operations = [
    ]
