# Generated by Django 4.2.7 on 2023-11-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_employee_email_employee_is_employee_superuser_and_more'),
        ('main_app', '0005_merge_0003_merge_20231128_1455_0004_employee_skills'),
    ]

    operations = [
    ]
