# Generated by Django 4.2.7 on 2023-11-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20231128_2315'),
        ('main_app', '0006_merge_20231129_1439'),
    ]

    operations = [
    ]
