# Generated by Django 4.2.7 on 2023-11-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_merge_20231129_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_employee_superuser',
        ),
    ]
